image: docker:latest

test_async:
  tags:
    - node33087
  only:
    - tags
  script:
    - echo "$SSH_PRIVATE_KEY"
    - echo $CI_COMMIT_TAG
    - echo $DOCKER_TOKEN
    - cat .dockerToken | docker login --username AWS --password-stdin 592907864864.dkr.ecr.us-east-1.amazonaws.com
    - ls -a
    - docker build -t emr_frontend . --no-cache
    - docker tag emr_frontend:latest 592907864864.dkr.ecr.us-east-1.amazonaws.com/emr_frontend:$CI_COMMIT_TAG
    - docker push 592907864864.dkr.ecr.us-east-1.amazonaws.com/emr_frontend:$CI_COMMIT_TAG
    - docker images -a
    - echo 'OK!!'
