//if add or remove variable, m_setToDefaultData alse need to change
export default {
  isMobile: false,
  isLoading: false,
  dialog: {
    show: false,
    title: "",
    content: "",
  },
  dakarModel: false,
  dakar: {
    Name: "",
    No: "",
    Token: "",
    RoleNos: [],
    Identities: null,
    FunctionNos: [],
    PartnerHospitals: [],
    ResponsibilityHospitals: [],
    IsAirReferralUser: false,
    IsFirstLogin: false,
    AppServer: "",
  },
  others: {},
  functions: [],
  isShowPwdDialog: false,
  diagnosisPatient: null,
  statusChangeEvents: {},
  checkIsLogin: 0,
  editItem: {},
  hasClickNotify: false,
  medicalCardData: "",
  setSearchFilter: {
    ApplyTimeStart: null,
    ApplyTimeEnd: null,
    InstitutionNo: null,
    "CreateAccount/Name": null,
    patientName: null,
    patientIdentifier: null,
    Status: [],
  },
};
