const DiagnosticReports = {
  ReportCategory: '報告類別',
  Category: '門住診別',
  PatientDepartment: '就醫科別代碼',
  PatientDepartmentName: '就醫科別名稱',
  ConditionCode: '主診斷碼',
  ConditionName: '主診斷名稱',
  BodySite: '診療部位',
  ResultCategory: '檢查檢驗類別',
  ResultCategoryDisplay: '檢查檢驗類別名稱',
  DRCode: '醫令代碼',
  DRCodeDisplay: '醫令名稱',
  ResultCode: '檢驗項目',
  ResultCodeDisplay: '檢驗方法',
  ResultValue: '檢查檢驗結果',
  ResultValueUnit: '單位',
  ResultReferenceRange: '參考值',
  Conclusion: '報告結果/病理發現及診斷',
  SpecimenCollectionMethod: '檢體採檢方法/來源/類別',
  EffectivePeriodStart: '開立醫令日期',
  EffectivePeriodEnd: '採檢/實際檢查日期',
  PerformerRoleSystem: '有無TAF認證',
  ImageComment: '是否有影像資料',
  CreateTime: '建立時間',
  CreatePractitionerId: '建立醫事人員ID',
  UpdateTime: '最後修改時間',
  UpdatePractitionerId: '最後修改醫事人員ID',
  IssuedDate: '報告日期',
  PayDate: '費用年月'
}

const MedicationRequests = {
  Code: '代碼',    
  Name: '名稱',    
  RouteCode: '途徑代碼',    
  RouteCodeName: '途徑名稱',    
  MethodCode: '服法代碼',    
  MethodCodeName: '服法名稱',    
  Dose: '次劑量',    
  DoseUnit: '次劑量單位',    
  Days: '日數(天)',    
  Total: '總量',    
  TotalUnit: '總量單位',    
  AuthoredOn: '就醫日期 (住院用藥起日)',    
  PractitionerId: '開單醫師',    
  OrganizationId: '開單單位',    
  ATC7Code: 'ATC7代碼',    
  ATC5Name: 'ATC5名稱',    
  IngredientCode: '成分代碼',    
  IngredientName: '成分名稱',    
  ConditionCode: '主診斷碼',    
  ConditionName: '主診斷名稱',    
  MedicationCode: '藥品代碼',    
  MedicationName: '藥品名稱',    
  DenominatorValue: '藥品規格量',    
  DenominatorUnit: '藥品規格量單位',    
  DosageInstructionText: '用法用量',    
  DosageInstructionDateEnd: '慢連箋領藥日(住院用藥迄日)',    
  DoseQuantity: '藥品用量',    
  TimingDuration: '給藥日數',    
  DrugMultiMark: '複方註記',    
  ListIdentifier: '就醫序號',    
  ATC3Name: 'ATC3Name',    
  RequesterOrgCode: '慢連箋原處方醫事機構代碼',    
  NumberOfRepeatsAllowed: '慢連籤',    
  MedicationCodeText: '基準方名',    
  Ingredient: '效能名',    
  Form: '劑型',    
  MaxDosePerAdministration: '給藥總量',    
  CreateTime: '建立時間',    
  CreatePractitionerId: '建立醫事人員ID',    
  UpdateTime: '最後修改時間',    
  UpdatePractitionerId: '最後修改醫事人員ID',    
  Source: '資料來源'
}

const Procedures = {
  PatientId: '病患Id',    
  ProcedureType: '類別',    
  ProcedureNo: '序號',    
  ProcedureCode: '代碼',    
  ProcedureName: '名稱',    
  StartDate: '起始日期',    
  EndDate: '結束日期',    
  AccessionNo: 'AccessionNo',    
  Dose: '次劑量',    
  DoseUnit: '次劑量單位',    
  Method: '服法',    
  Route: '途徑',    
  Days: '日數(天)',    
  Total: '總量',    
  TotalUnit: '總量單位',    
  ObservationValue: '量測結果值',    
  ObservationUnit: '量測單位',    
  ReferenceRangeLow: '量測最低值',    
  ReferenceRangeHigh: '量測最高值',    
  ReferenceText: '門住診別',
  PatientDepartment: '就醫科別代碼',    
  PatientDepartmentName: 'PatientDepartmentName',
  ConditionCode: '主診斷碼',
  ConditionName: '主診斷名稱',    
  PCode: '醫令代碼',    
  PCodeDisplay: '醫令名稱',    
  BodySite: '診療部位',    
  PPeriodStart: '就醫／檢查日期',    
  CreateTime: '建立時間',    
  CreatePractitionerId: '建立醫事人員ID',    
  UpdateTime: '最後修改時間',    
  UpdatePractitionerId: '最後修改醫事人員ID',    
  PFollowUpDate: '治療結束日期',    
  Source: '資料來源'
}

const Conditions = {
  No: 'No',
  Code: '代碼/診斷代碼',
  Name: '代碼名稱/診斷代碼名稱',
  Category: '類別/allergy過敏/diagnosis診斷/complaint病患主訴',
  AssertedDate: '發生日期/最近一次檢查日期',
  Evidence: '描述',
  PatientDepartment: '就醫科別代碼',
  PatientDepartmentName: 'PatientDepartmentName',
  ProcudeCode: '手術明細代碼/檢查及治療代碼',
  ProcudeCodeDisplay: '手術明細名稱/檢查及治療名稱',
  BodySite: '診療部位',
  PerformedPeriodStart: '執行時間-起',
  PerformedPeriodEnd: '執行時間-迄',
  CreateTime: '建立時間',
  CreatePractitionerId: '建立醫事人員ID',
  UpdateTime: '最後修改時間',
  UpdatePractitionerId: '最後修改醫事人員ID',
  Source: '資料來源'
}

export default {
  DiagnosticReports,
  MedicationRequests,
  Procedures,
  Conditions
}
