export const accountStatusItems = [
  { No: true, Name: '啟用' },
  { No: false, Name: '不啟用' },
]

export const zonesData = [
  {
    text: '基隆市',
    value: '基隆市',
    lat: '25.163946366420806',
    lng: '121.73743230657661',
    zone: ['仁愛區', '信義區', '中正區', '中山區', '安樂區', '暖暖區', '七堵區'],
  },
  {
    text: '臺北市',
    value: '臺北市',
    lat: '25.035759097898254',
    lng: '121.56491124600578',
    zone: [
      '中正區',
      '大同區',
      '中山區',
      '松山區',
      '大安區',
      '萬華區',
      '信義區',
      '士林區',
      '北投區',
      '內湖區',
      '南港區',
      '文山區',
    ],
  },
  {
    text: '新北市',
    value: '新北市',
    lat: '25.096371292306582',
    lng: '121.4599817561358',
    zone: [
      '萬里區',
      '金山區',
      '板橋區',
      '汐止區',
      '深坑區',
      '石碇區',
      '瑞芳區',
      '平溪區',
      '雙溪區',
      '貢寮區',
      '新店區',
      '坪林區',
      '烏來區',
      '永和區',
      '中和區',
      '土城區',
      '三峽區',
      '樹林區',
      '鶯歌區',
      '三重區',
      '新莊區',
      '泰山區',
      '林口區',
      '蘆洲區',
      '五股區',
      '八里區',
      '淡水區',
      '三芝區',
      '石門區',
    ],
  },
  {
    text: '桃園市',
    value: '桃園市',
    lat: '25.026390244563277',
    lng: '121.30561568034578',
    zone: [
      '中壢區',
      '平鎮區',
      '龍潭區',
      '楊梅區',
      '新屋區',
      '觀音區',
      '桃園區',
      '龜山區',
      '八德區',
      '大溪區',
      '復興區',
      '大園區',
      '蘆竹區',
    ],
  },
  {
    text: '新竹市',
    value: '新竹市',
    lat: '24.816940823142968',
    lng: '120.9679942132056',
    zone: ['東區', '北區', '香山區'],
  },
  {
    text: '新竹縣',
    value: '新竹縣',
    lat: '24.842145648820473',
    lng: '121.01858233606515',
    zone: [
      '竹北市',
      '湖口鄉',
      '新豐鄉',
      '新埔鎮',
      '關西鎮',
      '芎林鄉',
      '寶山鄉',
      '竹東鎮',
      '五峰鄉',
      '橫山鄉',
      '尖石鄉',
      '北埔鄉',
      '峨眉鄉',
    ],
  },
  {
    text: '苗栗縣',
    value: '苗栗縣',
    lat: '24.563277502951895',
    lng: '120.82125426653869',
    zone: [
      '竹南鎮',
      '頭份市',
      '三灣鄉',
      '南庄鄉',
      '獅潭鄉',
      '後龍鎮',
      '通霄鎮',
      '苑裡鎮',
      '苗栗市',
      '造橋鄉',
      '頭屋鄉',
      '公館鄉',
      '大湖鄉',
      '泰安鄉',
      '銅鑼鄉',
      '三義鄉',
      '西湖鄉',
      '卓蘭鎮',
    ],
  },
  {
    text: '臺中市',
    value: '臺中市',
    lat: '24.15070790922305',
    lng: '120.67296098052849',
    zone: [
      '中區',
      '東區',
      '南區',
      '西區',
      '北區',
      '北屯區',
      '西屯區',
      '南屯區',
      '太平區',
      '大里區',
      '霧峰區',
      '烏日區',
      '豐原區',
      '后里區',
      '石岡區',
      '東勢區',
      '和平區',
      '新社區',
      '潭子區',
      '大雅區',
      '神岡區',
      '大肚區',
      '沙鹿區',
      '龍井區',
      '梧棲區',
      '清水區',
      '大甲區',
      '外埔區',
      '大安區',
    ],
  },
  {
    text: '彰化縣',
    value: '彰化縣',
    lat: '24.05335986072244',
    lng: '120.51579130283484',
    zone: [
      '彰化市',
      '芬園鄉',
      '花壇鄉',
      '秀水鄉',
      '鹿港鎮',
      '福興鄉',
      '線西鄉',
      '和美鎮',
      '伸港鄉',
      '員林市',
      '社頭鄉',
      '永靖鄉',
      '埔心鄉',
      '溪湖鎮',
      '大村鄉',
      '埔鹽鄉',
      '田中鎮',
      '北斗鎮',
      '田尾鄉',
      '埤頭鄉',
      '溪州鄉',
      '竹塘鄉',
      '二林鎮',
      '大城鄉',
      '芳苑鄉',
      '二水鄉',
    ],
  },
  {
    text: '南投縣',
    value: '南投縣',
    lat: '23.965072611360778',
    lng: '120.97151990242308',
    zone: [
      '南投市',
      '中寮鄉',
      '草屯鎮',
      '國姓鄉',
      '埔里鎮',
      '仁愛鄉',
      '名間鄉',
      '集集鎮',
      '水里鄉',
      '魚池鄉',
      '信義鄉',
      '竹山鎮',
      '鹿谷鄉',
    ],
  },
  {
    text: '雲林縣',
    value: '雲林縣',
    lat: '23.712185589990405',
    lng: '120.43150838540335',
    zone: [
      '斗南鎮',
      '大埤鄉',
      '虎尾鎮',
      '土庫鎮',
      '褒忠鄉',
      '東勢鄉',
      '臺西鄉',
      '崙背鄉',
      '麥寮鄉',
      '斗六市',
      '林內鄉',
      '古坑鄉',
      '莿桐鄉',
      '西螺鎮',
      '二崙鄉',
      '北港鎮',
      '水林鄉',
      '口湖鄉',
      '四湖鄉',
      '元長鄉',
    ],
  },
  {
    text: '嘉義市',
    value: '嘉義市',
    lat: '23.483692414729695',
    lng: '120.44825241615193',
    zone: ['東區', '西區'],
  },
  {
    text: '嘉義縣',
    value: '嘉義縣',
    lat: '23.455460893087253',
    lng: '120.25494593876964',
    zone: [
      '番路鄉',
      '梅山鄉',
      '竹崎鄉',
      '阿里山鄉',
      '中埔鄉',
      '大埔鄉',
      '水上鄉',
      '鹿草鄉',
      '太保市',
      '朴子市',
      '東石鄉',
      '六腳鄉',
      '新港鄉',
      '民雄鄉',
      '大林鎮',
      '溪口鄉',
      '義竹鄉',
      '布袋鎮',
    ],
  },
  {
    text: '臺南市',
    value: '臺南市',
    lat: '23.003372322631215',
    lng: '120.22515860718215',
    zone: [
      '中西區',
      '東區',
      '南區',
      '北區',
      '安平區',
      '安南區',
      '永康區',
      '歸仁區',
      '新化區',
      '左鎮區',
      '玉井區',
      '楠西區',
      '南化區',
      '仁德區',
      '關廟區',
      '龍崎區',
      '官田區',
      '麻豆區',
      '佳里區',
      '西港區',
      '七股區',
      '將軍區',
      '學甲區',
      '北門區',
      '新營區',
      '後壁區',
      '白河區',
      '東山區',
      '六甲區',
      '下營區',
      '柳營區',
      '鹽水區',
      '善化區',
      '大內區',
      '山上區',
      '新市區',
      '安定區',
    ],
  },
  {
    text: '高雄市',
    value: '高雄市',
    lat: '22.62980972725341',
    lng: '120.30109139654347',
    zone: [
      '新興區',
      '前金區',
      '苓雅區',
      '鹽埕區',
      '鼓山區',
      '旗津區',
      '前鎮區',
      '三民區',
      '楠梓區',
      '小港區',
      '左營區',
      '仁武區',
      '大社區',
      '東沙群島',
      '南沙群島',
      '岡山區',
      '路竹區',
      '阿蓮區',
      '田寮區',
      '燕巢區',
      '橋頭區',
      '梓官區',
      '彌陀區',
      '永安區',
      '湖內區',
      '鳳山區',
      '大寮區',
      '林園區',
      '鳥松區',
      '大樹區',
      '旗山區',
      '美濃區',
      '六龜區',
      '內門區',
      '杉林區',
      '甲仙區',
      '桃源區',
      '那瑪夏區',
      '茂林區',
      '茄萣區',
    ],
  },
  {
    text: '屏東縣',
    value: '屏東縣',
    lat: '22.55561834245765',
    lng: '120.54772915073492',
    zone: [
      '屏東市',
      '三地門鄉',
      '霧臺鄉',
      '瑪家鄉',
      '九如鄉',
      '里港鄉',
      '高樹鄉',
      '鹽埔鄉',
      '長治鄉',
      '麟洛鄉',
      '竹田鄉',
      '內埔鄉',
      '萬丹鄉',
      '潮州鎮',
      '泰武鄉',
      '來義鄉',
      '萬巒鄉',
      '崁頂鄉',
      '新埤鄉',
      '南州鄉',
      '林邊鄉',
      '東港鎮',
      '琉球鄉',
      '佳冬鄉',
      '新園鄉',
      '枋寮鄉',
      '枋山鄉',
      '春日鄉',
      '獅子鄉',
      '車城鄉',
      '牡丹鄉',
      '恆春鎮',
      '滿州鄉',
    ],
  },
  {
    text: '臺東縣',
    value: '臺東縣',
    lat: '22.801355335288218',
    lng: '121.07051131316061',
    zone: [
      '臺東市',
      '綠島鄉',
      '蘭嶼鄉',
      '延平鄉',
      '卑南鄉',
      '鹿野鄉',
      '關山鎮',
      '海端鄉',
      '池上鄉',
      '東河鄉',
      '成功鎮',
      '長濱鄉',
      '太麻里鄉',
      '金峰鄉',
      '大武鄉',
      '達仁鄉',
    ],
  },
  {
    text: '花蓮縣',
    value: '花蓮縣',
    lat: '23.98982109189869',
    lng: '121.60157082528457',
    zone: [
      '花蓮市',
      '新城鄉',
      '秀林鄉',
      '吉安鄉',
      '壽豐鄉',
      '鳳林鎮',
      '光復鄉',
      '豐濱鄉',
      '瑞穗鄉',
      '萬榮鄉',
      '玉里鎮',
      '卓溪鄉',
      '富里鄉',
    ],
  },
  {
    text: '宜蘭縣',
    value: '宜蘭縣',
    lat: '24.705378189563206',
    lng: '121.73809295131261',
    zone: [
      '宜蘭市',
      '頭城鎮',
      '礁溪鄉',
      '壯圍鄉',
      '員山鄉',
      '羅東鎮',
      '三星鄉',
      '大同鄉',
      '五結鄉',
      '冬山鄉',
      '蘇澳鎮',
      '南澳鄉',
      '釣魚臺',
    ],
  },
  {
    text: '澎湖縣',
    value: '澎湖縣',
    lat: '23.573703352093275',
    lng: '119.5793151234149',
    zone: ['馬公市', '西嶼鄉', '望安鄉', '七美鄉', '白沙鄉', '湖西鄉'],
  },
  {
    text: '金門縣',
    value: '金門縣',
    lat: '24.452181341411034',
    lng: '118.375947981912',
    zone: ['金沙鎮', '金湖鎮', '金寧鄉', '金城鎮', '烈嶼鄉', '烏坵鄉'],
  },
  {
    text: '連江縣',
    value: '連江縣',
    lat: '26.164244681618403',
    lng: '119.9525229424052',
    zone: ['南竿鄉', '北竿鄉', '莒光鄉', '東引鄉'],
  },
]

export const genderCodeItems = [
  { label: '男', value: 'M' },
  { label: '女', value: 'F' },
]

export const activeStatusItems = [
  { label: '啟用', value: true },
  { label: '不啟用', value: false },
]

export const activeStatusNumberItems = [
  { label: '啟用', value: 1 },
  { label: '不啟用', value: 0 },
]

export const activeEditNumberItems = [
  { label: '新增', value: 0 },
  { label: '編輯', value: 1 },
  { label: '刪除', value: 2 },
  { label: '查詢', value: 3 },
]

export const bloodTypeItems = [
  { value: 'A', label: 'A' },
  { value: 'B', label: 'B' },
  { value: 'AB', label: 'AB' },
  { value: 'O', label: 'O' },
  { value: 'Rh+', label: 'Rh+' },
  { value: 'Rh-', label: 'Rh-' },
]

export const marriageStatusItems = [
  { value: 'N', label: '未婚' },
  { value: 'Y', label: '已婚' },
]

export const yesOrNoItems = [
  { label: '否', value: false },
  { label: '是', value: true },
]

export const withOrWithoutItems = [
  { label: '無', value: false },
  { label: '有', value: true },
]

export const weekNameItems = [
  {
    EName: 'SUN',
    CName: '星期日',
    NumName: 0,
  },
  {
    EName: 'MON',
    CName: '星期一',
    NumName: 1,
  },
  {
    EName: 'TUE',
    CName: '星期二',
    NumName: 2,
  },
  {
    EName: 'WED',
    CName: '星期三',
    NumName: 3,
  },
  {
    EName: 'THU',
    CName: '星期四',
    NumName: 4,
  },
  {
    EName: 'FRI',
    CName: '星期五',
    NumName: 5,
  },
  {
    EName: 'SAT',
    CName: '星期六',
    NumName: 6,
  },
]

export const monthItems = [
  {
    label: '1 月',
    value: 1,
  },
  {
    label: '2 月',
    value: 2,
  },
  {
    label: '3 月',
    value: 3,
  },
  {
    label: '4 月',
    value: 4,
  },
  {
    label: '5 月',
    value: 5,
  },
  {
    label: '6 月',
    value: 6,
  },
  {
    label: '7 月',
    value: 7,
  },
  {
    label: '8 月',
    value: 8,
  },
  {
    label: '9 月',
    value: 9,
  },
  {
    label: '10 月',
    value: 10,
  },
  {
    label: '11 月',
    value: 11,
  },
  {
    label: '12 月',
    value: 12,
  },
]

export const blockHotkeyItems = [
  ['Control', 'Escape'],
  ['Shift', 'Escape'],
  ['Alt', 'Escape'],
  ['Control', 'Tab'],
  ['Shift', '!'],
  ['Alt', 'F4'],
  ['Control', 'CapsLock'],
  ['Shift', '@'],
  ['Alt', 'Tab'],
  ['Control', 'Enter'],
  ['Shift', '#'],
  ['Alt', 'CapsLock'],
  ['Control', 'Shift'],
  ['Shift', '$'],
  ['Alt', 'Enter'],
  ['Control', 'F4'],
  ['Shift', '%'],
  ['Alt', 'Shift'],
  ['Control', '/'],
  ['Shift', '^'],
  ['Alt', 'ArrowUp'],
  ['Control', 'ArrowUp'],
  ['Shift', '&'],
  ['Alt', 'ArrowDown'],
  ['Control', 'ArrowDown'],
  ['Shift', '*'],
  ['Alt', 'ArrowLeft'],
  ['Control', 'ArrowLeft'],
  ['Shift', '('],
  ['Alt', 'ArrowRight'],
  ['Control', 'ArrowRight'],
  ['Shift', ')'],
  ['Alt', 'Insert'],
  ['Control', 'Insert'],
  ['Shift', '_'],
  ['Alt', 'Home'],
  ['Control', 'Home'],
  ['Shift', '+'],
  ['Alt', 'PageUp'],
  ['Control', 'PageUp'],
  ['Shift', 'Tab'],
  ['Alt', 'PageDown'],
  ['Control', 'PageDown'],
  ['Shift', '{'],
  ['Alt', 'Delete'],
  ['Control', 'Delete'],
  ['Shift', '}'],
  ['Alt', 'End'],
  ['Control', 'End'],
  ['Shift', '|'],
  ['Alt', 'NumLock'],
  ['Control', 'NumLock'],
  ['Control', 'Pause'],
  ['Shift', 'CapsLock'],
  ['Control', 'E'],
  ['Shift', ':'],
  ['Control', 'F'],
  ['Shift', 'Enter'],
  ['Control', 'J'],
  ['Shift', '<'],
  ['Control', 'K'],
  ['Shift', '>'],
  ['Control', 'N'],
  ['Shift', '?'],
  ['Control', 'P'],
  ['Shift', '/'],
  ['Control', 'T'],
  ['Shift', '-'],
  ['Control', 'W'],
  ['Shift', 'Control'],
  ['Control', 'Y'],
  ['Shift', 'Alt'],
  ['Control', 'Z'],
  ['Shift', 'Insert'],
  ['Shift', 'Home'],
  ['Shift', 'PageUp'],
  ['Shift', 'PageDown'],
  ['Shift', 'End'],
  ['Shift', 'Delete'],
  ['Shift', 'ArrowUp'],
  ['Shift', 'ArrowDown'],
  ['Shift', 'ArrowLeft'],
  ['Shift', 'ArrowRight'],
  ['Shift', 'NumLock'],
  ['Shift', '"'],
]

export const timeSlotItems = [
  { value: '1', label: '上午' },
  { value: '2', label: '下午' },
  { value: '3', label: '夜間' },
]

